export const background = '/background.png'
export const capahome = '/capahome.png'
export const logohome = '/logohome.png'
export const caretright = '/BiCaretRight.svg'
export const menu = '/menu.svg'
